@InvoiceSystem_HostAddress = http://localhost:5270
GET {{InvoiceSystem_HostAddress}}/weatherforecast/
Accept: application/json

/* Get & create products */

### Get all products
GET {{InvoiceSystem_HostAddress}}/api/products
Accept: application/json

### Create Herend trophy

POST {{InvoiceSystem_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Herend Trophy for Formula 1",
    "category": "Trophy",
    "unitPrice": 15000000,
    "isHazardous": true,
    "isDiscountEligible": false
}

### Create IKEA glass bottle

POST {{InvoiceSystem_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "IKEA glass bottle",
    "category": "Home furniture",
    "unitPrice": 1200,
    "isHazardous": true,
    "isDiscountEligible": true
}

/* Get & create customers */

### Get all customers

GET {{InvoiceSystem_HostAddress}}/api/customers
Accept: application/json

### Create customer - Lando Norris

POST {{InvoiceSystem_HostAddress}}/api/customers
Content-Type: application/json

{
    "name": "Lando Norris",
    "country": "United Kingdom",
    "address": "M14 6QL Manchester, 27 Maplewood Road"
}

### Create customer - Henry Cavill

POST {{InvoiceSystem_HostAddress}}/api/customers
Content-Type: application/json

{
    "name": "Henry Cavill",
    "country": "United Kingdom",
    "address": "B15 2TT Birmingham, 42 Oakfield Road"
}

